### ISSUE TITLE
API endpoint /os broken

### ISSUE THREAD

**Issue by luisfavila** [cp6/my-idlers#104]
When doing `GET /os` (and using APP_DEBUG=true) you get the following:
```
Call to a member function toJson() on array
```
![image](https://github.com/cp6/my-idlers/assets/15204687/eac50a21-a96d-45e7-85d6-1eb0471079ae)

**Comment by cp6** [comment]
Thanks, fixed this here https://github.com/cp6/my-idlers/commit/5797e8c30a41b412beef458f227386688369bcb8
