### ISSUE TITLE
Provider - Custom

### ISSUE THREAD

**Issue by dribgnikcom** [cp6/my-idlers#117]
I apologize if this has been covered before...

But would you please consider the possibility of an "other" option (accompanied by a dynamic textbox) to specify providers that are not listed?  It would also be nice to have that for the location and label fields.

Thanks

**Comment by Lucifer1590** [comment]
you can add your own providers already more>>provider>> add a new provider

**Comment by dribgnikcom** [comment]
Oops, I did not see that.  Thanks very much, I greatly appreciate it.
