### ISSUE TITLE
How To Purge The Registered User

### ISSUE THREAD

**Issue by dribgnikcom** [cp6/my-idlers#118]
I am trying to install the dev3 branch, but when I try to access the page, it is displaying the login screen instead of the register screen.  Trying to directly access 'register' redirects me to login.

I removed the my-idlers directory and also dropped the my_idlers database from SQL, yet this persists.

Thanks

**Comment by Cryptominer937** [comment]
Just need to remove the existing user from the database and it will load the registration page.

**Comment by dribgnikcom** [comment]
Thanks - yes it seems like it has nothing to do with not purging it successfully and more to do with the dev3 build...

I am trying to install the dev3 build because I think there are issues with the stable build and the latest Debian/PHP.  The problem is that after I git clone and install it, I am stuck at the login screen.

Maybe I ought to try to transplant user credentials from a working build.
