### ISSUE TITLE
Cards Broken in dev branch

### ISSUE THREAD

**Issue by Mio-sha512** [cp6/my-idlers#13]
If you try too see servers/domains in the dev branch they won't show up unless you click "Switch to cards"

**Comment by cp6** [comment]
Further detail/desciption please?

**Comment by Mio-sha512** [comment]
Here is what im talking about https://youtu.be/k2jaYe7qpag

**Comment by cp6** [comment]
Ok thanks. Did you also get the `scripts.min.js` and `calls.php` file? also make sure that the scripts.min.js file isnt cached.

[c882d4702656cd5568b379f93c591b9252539e9d](https://github.com/cp6/my-idlers/commit/c882d4702656cd5568b379f93c591b9252539e9d)

**Comment by Mio-sha512** [comment]
It was just cloudflare caching the files.
