### ISSUE TITLE
Parse error: syntax error class.php on line 3091

### ISSUE THREAD

**Issue by lamasaiedhussien** [cp6/my-idlers#18]
Running PHP 7.4 and getting this error looks related to the YABS function.

`Parse error: syntax error, unexpected 'string' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) in /home/public_html/class.php on line 3091`

**Comment by cp6** [comment]
From the latest version line 3091 of class.php is a call to the daysAway() function. I have a feeling due date field was left empty?

**Comment by lamasaiedhussien** [comment]
Should I have put a date? This was a fresh install and got that error right out of the gate

**Comment by cp6** [comment]
No, it shouldn't have to have a date. The date being empty was something i saw as a possibility from reading the code as there is no check for that. Did you get the error inserting a server or was it just there at the homepage?

**Comment by lamasaiedhussien** [comment]
It was on the home page, I imported the DB and edited the class to include the DB details then uploaded the files and go the error. I will add that I have to edit the .sql to change the name of the DB, not sure if that could have caused this. When I tried to import it did a if idlers doesn't exist create but it can't create it because of the name.
