### ISSUE TITLE
Dateformat

### ISSUE THREAD

**Issue by rv545** [cp6/my-idlers#19]
Make the dateformat a configurable option. Most of the world actually hates the mm/dd/yyyy format since it makes absolutely no sense. 

If it's not possible to make it a configuration option, then please follow international standards. https://en.wikipedia.org/wiki/ISO_8601

**Comment by cp6** [comment]
Do you mean the date type inputs?

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date

That is just standard across the web and a custom interface is used for each browser to select the date.
