### ISSUE TITLE
SUM cards error with different units

### ISSUE THREAD

**Issue by Gamerboy59** [cp6/my-idlers#33]
When I add a server with 24GB RAM and another server with 5GB RAM, the sum card on the dashboard will show something like `2.9E-5 GB` If I create the server with the same amount specified in MB (not GB) RAM I'm getting a more realistic result.
This appears to be an error in unit conversion.

**Comment by cp6** [comment]
Should be fixed [here](https://github.com/cp6/my-idlers/commit/f3c3d3a9f300d8b97f839c1df4a579bca0610bc2) and [here](https://github.com/cp6/my-idlers/commit/35f96a6ee60623b802a6df8329324d6e3bf7c8d9) ?

**Comment by Gamerboy59** [comment]
Thanks, this fixed it on the dashboard.
