### ISSUE TITLE
missing Virt list editor

### ISSUE THREAD

**Issue by louis-eyond** [cp6/my-idlers#41]
We have VMware on a few servers, but it's not in the Virt list and there doesn't seem to be a UI option to edit this list.

**Comment by cp6** [comment]
[I just added this option for the next version](https://github.com/cp6/my-idlers/commit/da34256194be3470c1e0593040dc570e34f3a1d0).

As there are only several options I didn't think it was worth the hassle to build a CRUD for it (like Locations, providers and OS).
