### ISSUE TITLE
Currency in dashboard

### ISSUE THREAD

**Issue by devsorice** [cp6/my-idlers#45]
Hi i don't know if it is possible,
i'm able to change the default currency in euro,
but that settings only applies to servers and domains etc..
Is there a way to change the currency displayed in the dashboard?
Thank you for your help.

**Comment by cp6** [comment]
> Is there a way to change the currency displayed in the dashboard?

Do you mean on the homepage in the summary cards (Weekly cost, Monthly cost etc)?

If so i have done this in these commits: [One](https://github.com/cp6/my-idlers/commit/319be38fa9558d742a599839cca739e3f81082b6) & [Two](https://github.com/cp6/my-idlers/commit/73f2d8f07f151b139b1a21a812f3017af48c6ebf)

Remember to run `php artisan migrate` to create the column in the settings table

**Comment by devsorice** [comment]
Perfect, i pulled the dev branch and it worked like a charm, thank you!
Totals seems to be a little bit off (like 5% than the actual some), but maybe it's because of double conversion?

Btw If you need an api for currencies, these are the official sources that i use:
US Federal Reserve (USD to other currencies)
https://www.federalreserve.gov/feeds/data/H10_H10.XML
European Central Bank (EUR to other currencies)
https://www.ecb.europa.eu/stats/eurofxref/eurofxref-hist-90d.xml
