### ISSUE TITLE
Property "price" missing

### ISSUE THREAD

**Issue by Gamerboy59** [cp6/my-idlers#56]
Since v2.1.2 I'm getting an error `Attempt to read property "price" on null` when accessing https://domain.com/<server|shared|reseller|domains...> I was running the migration but this appears to be still missing (hence null).

**Comment by cp6** [comment]
Did you also run

```php artisan route:cache```

```php artisan cache:clear```

After updating?

**Comment by Gamerboy59** [comment]
Yes, all migrations have been performed, too.

**Comment by Gamerboy59** [comment]
`Attempt to read property \"price\" on null at /home/<user>/laravel-backend/resources/views/servers/index.blade.php:80`

**Comment by cp6** [comment]
Possibly fixed now: [20058cb9c9147105e5187fdccb9ea1e9bd55bd09](https://github.com/cp6/my-idlers/commit/20058cb9c9147105e5187fdccb9ea1e9bd55bd09) ?

Needed to define the keys as a string for Sqlite
