### ISSUE TITLE
Unsupported method GET for dashboard

### ISSUE THREAD

**Issue by Gamerboy59** [cp6/my-idlers#57]
Since v2.1.2 I'm getting the following error when trying to access https://domain.com/ (or /dashboard):
`The GET method is not supported for this route. Supported methods: HEAD.` This error appears before being logged in (e.g. private tab) as well as after having logged in (/login is working).

**Comment by cp6** [comment]
Did you run

```php artisan route:cache```
```php artisan cache:clear``

Aftter updating?

**Comment by Gamerboy59** [comment]
Yes, all steps of the upgrade instructions in the `README.md` have been executed. I just executed them again but this didn't fix it. Doing a completely new installation and just copying over the sqlite-db and the .env lead to the same result.

**Comment by cp6** [comment]
Ok, thanks. Interesting, these arent happening with MySQL ill switch over to Sqlite and have a look

**Comment by cp6** [comment]
Possibly fixed now: [20058cb9c9147105e5187fdccb9ea1e9bd55bd09](https://github.com/cp6/my-idlers/commit/20058cb9c9147105e5187fdccb9ea1e9bd55bd09) ?

Needed to define the keys as a string for Sqlite

**Comment by Gamerboy59** [comment]
This has fixed many issues but not: `The GET method is not supported for this route. Supported methods: HEAD.` on route ("/" or dashboard)

**Comment by cp6** [comment]
Searching that error up just brings commands:

php artisan optimize

and/or

php artisan cache:clear
php artisan route:cache  
php artisan config:cache  
php artisan view:clear

**Comment by cp6** [comment]
What environment are you hosting it in?

**Comment by Gamerboy59** [comment]
It's a standard cPanel shared hosting. my-idlers used to work until the recent update. I just executed the optimize command but this didn't help.

**Comment by Gamerboy59** [comment]
Only the index / home page is effected. The pages for server, shared, resellers, settings etc. are working fine.

**Comment by Gamerboy59** [comment]
I noticed this issue is happening on new installations only. Upgrading my existing installation works fine. Maybe a bug at the dependencies?

**Comment by cp6** [comment]
@Gamerboy59 I'm really unsure, I cant reproduce it. Was thinking it was something to do with the shared hosting handling redirects weirdly.

**Comment by Gamerboy59** [comment]
I just found the solution. The optimization has an additional cache which needs to be wiped too. Now it's working.

```
php artisan optimize:clear
php artisan route:clear
```
