### ISSUE TITLE
feature request: sort by due date

### ISSUE THREAD

**Issue by imlonghao** [cp6/my-idlers#66]
Those pages `/servers`, `/shared`, and so on, currently is sorted by the random ID.

It would be better those pages can be sorted by the due date so we can know which server is going to expired.

**Comment by cp6** [comment]
In progress: https://github.com/cp6/my-idlers/pull/70

**Comment by imlonghao** [comment]
I found this which can sort table in front-end
https://www.kryogenix.org/code/browser/sorttable/

just FYI

**Comment by cp6** [comment]
Thanks for that, ill stick with the backend sorting for now as a front-end library may likely struggle when the dates are formatted to human readable strings

**Comment by imlonghao** [comment]
https://www.kryogenix.org/code/browser/sorttable/#customkeys

**Comment by imlonghao** [comment]
I tried the latest version, the server order seems still fixed to me no matter how I change the order setting.

**Comment by cp6** [comment]
Was an issue with the price relationship have got this working https://github.com/cp6/my-idlers/commit/beaf9af041c56701f3f12c1517485a75ca4020b4

**Comment by imlonghao** [comment]
The Server page work as expected after change the order setting,
but it seems you forget to clear the cache for the Domain page.

**Comment by cp6** [comment]
> you forget to clear the cache for the Domain page.

Fixed here https://github.com/cp6/my-idlers/commit/a20ce989dcf4940de262ff9bb89cc58252f8a46e

**Comment by imlonghao** [comment]
LGTM
