### ISSUE TITLE
server_type and virt

### ISSUE THREAD

**Issue by imlonghao** [cp6/my-idlers#69]
server_type and virt are very weird

virt doesn't exist in the databases

when editing a server, server_type and virt are using the same form selector name `server_type`

You may want to remove the `virt` field on the server create and server edit page

**Comment by cp6** [comment]
Thanks for picking this up, fixed here [41413a224f3d3f81a3ee017d308157d503d76d1c](https://github.com/cp6/my-idlers/commit/41413a224f3d3f81a3ee017d308157d503d76d1c)
