### ISSUE TITLE
May remove the "Add a YABs" button on servers page

### ISSUE THREAD

**Issue by kerm-me** [cp6/my-idlers#72]
Since `yabs/create` return 404 now, It is a little confusing.

**Comment by cp6** [comment]
Thanks, good find!

**Comment by kerm-me** [comment]
There is another `add a YABs` link on individual server page.
If possible, I perfer to pop-up a modal when click it, just like:

    run this script on your server to add a yabs
    `curl -sL yabs.sh | bash -s -- -s "URL/api/yabs/SERVERID/APIKEY"`

**Comment by cp6** [comment]
https://github.com/cp6/my-idlers/commit/17b7733258bfb10098418bde9daff1f189276e66 

and

https://github.com/cp6/my-idlers/commit/a56424bcaf6d70f4c16112fdc7bd207a3577a4a6
