### ISSUE TITLE
Show ASN information for IPs

### ISSUE THREAD

**Issue by Brueggus** [cp6/my-idlers#8]
It would be great if ASN information could be stored and displayed for example on mouseover over an IPv4/6 address.

Instead of entering these values manually, you could check if the `geoip` module is available and use https://www.php.net/manual/de/function.geoip-asnum-by-name.php for lookups.

**Comment by Brueggus** [comment]
I did some tests and using the geoip module seems to be a bad idea for some reasons. For example, it does not properly support IPv6. I'll look into some alternatives and will eventually open a PR. :)

**Comment by cp6** [comment]
I can host the data from [here](https://iptoasn.com/) an example:[https://api.srv3r.com/asn/?ipv4=8.8.8.8](https://api.srv3r.com/asn/?ipv4=8.8.8.8)
