### ISSUE TITLE
Bug: Dark And Light css files missing

### ISSUE THREAD

**Issue by kgotso** [cp6/my-idlers#80]
There seems to be a change related to how the light and dark themes are treated causing the latest build to fail to pull the correct file and render the page correctly 

Error 404 on the following paths:
/css/light.css
/css/dark.css

**Comment by cp6** [comment]
Thanks for letting me know, what kind of environment are you using for the application? I recently changed to NPM/webpack for the CSS and JS https://github.com/cp6/my-idlers/commit/0f0b06ee4799b8add8185b6fc7292216d6463280

**Comment by morreke** [comment]
Same problem here with latest docker image, version [322898e](https://github.com/users/cp6/packages/container/my-idlers/49917473?tag=322898e) is still working indeed

**Comment by cp6** [comment]
Updated the project to now include the compiled assets rather than require it to be done manually, Is it loading correctly now?

**Comment by morreke** [comment]
Yes can confirm, lastest tag is working again on docker
Thanks for fixing
