### ISSUE TITLE
New Locations Are Not Alpha-Sorted Correctly

### ISSUE THREAD

**Issue by raindog308** [cp6/my-idlers#89]
After adding "Hillsboro, OR" to my locations, it shows up as a valid choice in Servers, but at the very end of the list, instead of appearing between "Helsinki, Finland" and "Hong Kong" as expected.

Very minor - nice project!  Greetings from LowEndTalk 👍 💚

**Comment by cp6** [comment]
Thanks for raising this, [Fixed here](https://github.com/cp6/my-idlers/commit/c24056c511733e92d5b1528df49edda89f644a0b)!

You will need to clear the cache for this to regenerate the lists alpha sorted `php artisan cache:clear`
