### ISSUE TITLE
DNS Lookup not working

### ISSUE THREAD

**Issue by asimzeeshan** [cp6/my-idlers#9]
DNS lookup is not working

```
calls.php?type=A&hostname=vps.domain.ext
```

the issue is in calls.php file https://github.com/cp6/my-idlers/blob/aa4a4f9b0dcffb4ba3472ab984d15b16222880fe/calls.php#L39

should be replaced with

```
        } elseif ($_GET['type'] == 'A' || $_GET['type'] == 'AAAA') {
```

Also on a side note, PHP now has a function to get DNS records (https://www.php.net/manual/en/function.dns-get-record.php), I will advise you to use these (they return array)

```
# get only A record
dns_get_record($_GET['hostname'], DNS_A);

# get only AAAA record
dns_get_record($_GET['hostname'], DNS_AAAA);

# get both A and AAAA records
dns_get_record($_GET['hostname'], DNS_A + DNS_AAAA);

```

**Comment by cp6** [comment]
Thanks @asimzeeshan 

[e876d93005e3313fbb0698c87cae8571c6af4c97](https://github.com/cp6/my-idlers/commit/e876d93005e3313fbb0698c87cae8571c6af4c97)

I see that you tried a fix.

The inbuilt DNS functions is in [this issue](https://github.com/cp6/my-idlers/issues/7)

**Comment by asimzeeshan** [comment]
Awesome!!!

Creating a pull request for dns_get_record() proposed changes

**Comment by asimzeeshan** [comment]
Updated pull request (https://github.com/cp6/my-idlers/pull/10) with class.php code, here are my changes for the native DNS lookup

a89f624b082a81a7dc4d8deef7c33964a849b40c
