### ISSUE TITLE
Arm support

### ISSUE THREAD

**Issue by Sayyiku** [cp6/my-idlers#90]
## Is there a plan for Arm's adaptation?

<img width="1273" alt="image" src="https://user-images.githubusercontent.com/77047823/227821581-8e8b0bad-9740-4051-a127-351088f920d1.png">

**Comment by johnny12150** [comment]
Maybe you can build the docker image by yourself?

**Comment by kastoreon** [comment]
@Sayyiku

git clone the repo and the following to your docker-compose.yml file instead of image:

build:
      context: ./my-idlers (directory to git dir)
      dockerfile: Dockerfile
