### ISSUE TITLE
Do not include inactive services in calculation for dashboard

### ISSUE THREAD

**Issue by Gamerboy59** [cp6/my-idlers#93]
I noticed that the calculations at the dashboard (ram, storage, prices etc.) account inactive services too. It makes more sense to me if inactive services are excluded from the dashboard so one can get a quick overview over the current sitation and not for everything that is in the database.

**Comment by cp6** [comment]
Good pick up. I had a look and from what I can see the only one that includes inactive is the pricing.
I can get around to fixing this soon

**Comment by cp6** [comment]
It could also be a cache issue if you find this effects the specs

**Comment by Gamerboy59** [comment]
> Good pick up. I had a look and from what I can see the only one that includes inactive is the pricing. I can get around to fixing this soon

Yes, it's the pricing only apparently.

**Comment by cp6** [comment]
Should be fixed now

https://github.com/cp6/my-idlers/commit/171eb63b9aecfc96a700ca287b3c84532ac54c29

**Comment by AnyDomainLLC** [comment]
It actually does not seem that this issue is resolved.

I am still seeing inactive services included in the pricing.
