### ISSUE TITLE
Attempt to read property "name" on array

### ISSUE THREAD

**Issue by Gamerboy59** [cp6/my-idlers#94]
This error occures on the providers, os and locations blade (general blade as well as component blade). It looks like the function e.g. `OS::allOS();` returns a list of arrays which is accessed like an object instead as array.

This one here is just an example but almost all blades are effected: https://github.com/cp6/my-idlers/blob/6bbbc232bd081449a2fda45ccaa5a34ce5971478/resources/views/os/index.blade.php#L21

**Comment by cp6** [comment]
Thank you for finding this

https://github.com/cp6/my-idlers/commit/ec2947936b4634162f07d602e5f3bceb2b99a468

**Comment by Gamerboy59** [comment]
Components part solved by #95
