### ISSUE TITLE
hub.docker.com?

### ISSUE THREAD

**Issue by pallebone** [cp6/my-idlers#96]
Hi there,

I dont see this project on hub.docker.com. Can I put it there if you do not intend to do so?

Kind regards
Peter

**Comment by cp6** [comment]
Hi Peter
Yes I have no issues with you putting it on there, thank you for asking!

**Comment by pallebone** [comment]
Thank you. I will look into it then :)

**Comment by pallebone** [comment]
Hi I got busy and never did this. Just letting you know I never got around to it.
