### ISSUE TITLE
Interface does not display monthly cost

### ISSUE THREAD

**Issue by maticboncina** [cp6/my-idlers#97]
Hello,

I am wondering, despite entering prices (though in different currencies) at each service, why are they not shown on the home page under "monthly cost"?

Best, Matic

**Comment by cp6** [comment]
Hello Matic
Thank you for finding this
This should be fixed now https://github.com/cp6/my-idlers/commit/b2595fc9207f5230581b0836af6b1f5eafc7fe50

Regards
